# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Main

on:
  push:
    branches:
    - main

jobs:
  cypress:
    name: Cypress CI-CD Execution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          always-auth: true
          cache: 'npm'
          
      - name:  Install dependencie
        run: npm install
          
      - uses: cypress-io/github-action@v4
        with:
          command: npm run cy:run

      - name: Upload cypress report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-report
          path: mochawesome-report/
